### ISSUE TITLE
Icon not shown in Plugin Installer

### ISSUE THREAD

**Issue by Meisterlala** [Felys1998/EnemyListDebuffs#2]
The Icon for the Plugin doesn't show up in the Plugin Installer.

![image](https://user-images.githubusercontent.com/6453306/191015634-50dd47fb-a695-48f0-b922-bec9476dee94.png)

You can fix that by making the icon image square. Its currently 60x57 pixels

![image](https://user-images.githubusercontent.com/6453306/191015828-e882ce88-3f42-4fbf-b63a-2a0b9ae5f818.png)

**Comment by Felys1998** [comment]
I'm aware. Been lazy, will fix whenever the plugin requires a new push.

**Comment by Felys1998** [comment]
Fixed in 0.3.7.0
