### ISSUE TITLE
Allow users to resize the ImGUI settings window

### ISSUE THREAD

**Issue by ryankhart** [Felys1998/EnemyListDebuffs#5]
I use a global font scale of 200% because I play on a 4K TV sitting across the room. But a negative side effect of that is that some Dalamud plugins do not work well with that font scaling, especially if I can't manually resize the windows. In your settings window, much of the text is cut off, and I can't read it. 

This is what mine looks like:
![image](https://github.com/Felys1998/EnemyListDebuffs/assets/3673962/cccb98c5-3815-4ad5-8c08-34ca4d62cdac)

**Comment by Felys1998** [comment]
Sorry haven't been actively monitoring things. I think I know where to change to fix this. I'll test it out tomorrow.

**Comment by ryankhart** [comment]
That's ok. I expect nothing when I make these issues on GitHub projects. I just see it as an idea backlog that I'm contributing to. If it bugged be bad enough, I would have dove into the code and made a pull request for you already, but I'm currently on a break from FFXIV right now playing Path of Exile.

**Comment by Felys1998** [comment]
Got it tested but there was a hotfix patch so I delayed pulling D17. I'll get to that this week after a post patch test.

**Comment by Felys1998** [comment]
Update got pulled in to stable, should be good to go!
